name: Deploy VitePress with pnpm

on:
  push:
    branches:
      - main # 或你默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 23.11.1
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.1
          cache: "pnpm" # ✅ 自动缓存 node_modules，加快安装速度

      - name: Setup pnpm 10.11.0
        uses: pnpm/action-setup@v2
        with:
          version: 10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Build docs
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
